version: '3'
services:
    mongodb:
        container_name: mongo_tpb
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - "27017:27017"

#    mongo_import:
#        image: mongo:latest
#        links:
#            - mongodb
#        volumes:
#            - ./:/app
#        command:
#            ./app/entrypoint.sh